# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18G2YfanpU5w4gCvPLYQlWBiqluTF7JKV
"""

2
#Solicite ao usuario para digitar um numero e converte o valor para interio

a = int (input("digite o numero"))
# solicite que o usuario digite o numero
b = 0
c = 7

if a > b: print("este numero é negativo")
else:
 print("este numero é positivo")

3
#Solicite ao usuario para digitar um numero e converte o valor para interio

s = input("digite seu sexo f para feminino e m para masculino")
# solicite que o usuario digite o sexo
if s == "m" or "M" == s:
   print("sexo masculino")

elif s == "f" or "F" == s:
    print("sexo feminino")

else:
    print("sexo invalido")

4
J=(input ("digite uma letra"))
# solicite que o usuario digite uma letra
if J==  ("A") or J== ("E") or J== ("I") or J== ("O") or J== ("U") or J== "a" or J== "e" or J== "i" or J== "o" or J== "u":
 print("é uma vogal")

else:print ("não é uma vogal")

5
nota1 = float(input("digite a primeira nota"))
nota2 = float(input ("digite sua segunda nota"))

media = (nota1 + nota2)/2

if media >= 7 and media <= 10:
  print("voce foi aprovado")
elif media == 10:
  print("aprovado com distinção")
else:
  print("reprovado")

6
a = (input("digite o primeiro numero"))
b = (input("digite o segundo numero"))
c = (input("digite o terceiro numero"))

if a>b and a>c:
  print("a é o maior numero")
elif b > a and b > c:
  print("b e o maior numero")
else:
 print("c e o maior numero ")

if a<b and a<c:
  print("a é o menor numero")
elif b < a and b < c:
  print("b e o menor numero")
else:
 print("c e o menor numero ")

7
# Solicita ao usuário que insira o preço do primeiro produto
a = (input("Por favor, insira o preço do primeiro produto: "))
# Solicita ao usuário que insira o preço do segundo produto
b = (input("Por favor, insira o preço do segundo produto: "))
# Solicita ao usuário que insira o preço do terceiro produto
c = (input("Por favor, insira o preço do terceiro produto: "))

menor = a

if b < menor:
    menor = b
if c < menor:
    menor = c

if menor == a:
    print("O produto mais barato é o primeiro, que custa", a)
elif menor == b:
    print("O produto mais barato é o segundo, que custa", b)
else:
    print("O produto mais barato é o terceiro, que custa", c)

8
a = input("digite um numero")
b = input("digite um numero")
c = input("digite um numero")

if a > b and a > c
maior = a
print = ("a ordem e a b c")

elif b > a and >c
maior = a ordem e b a c


print ("a ordem c b a")

9
a = (input ("manha"))
b = (input ("tarde"))
c = (input ("noite"))

if = a
print ("ola, bom dia")

if  b
print ("ola, boa tarde")

elif: = c
print ("ola, boa noite")

else:
print = ("opcao invalida")

10
a = input ("digite um numero")
b = input ("digite um numero")

if = a > b
print ("a e o maior numero")

else:
print ("b e o maior numero")

11
opcao = (input("digite o numero do dia da semana d"))
# solicite que o usuario digite o numero da semana

if opcao ==1:
  print("domingo")
elif numero == 2:
 print("segunda")
elif numero == 3:
 print("terca")
elif numero == 4:
 print("quarta")
elif numero == 5:
 print("quinta")
elif numero == 6:
 print("sexta")
elif numero == 7:
 print("sabado")

Maior numero = 0
For i in range (5)
Numero  = input ("digite o primeiro numero")
if numero > maior numero

maior numero > numero

2
for contador in range(1000, 2001):
 if contador % 11 == 2:
  print(contador)

3
soma = 0
for i in range(5):
  numero = float(input(f"digite o {i+1}º numero: "))
  soma += numero
media = soma/5
print(f"A soma dos numeros e: {soma}")
print(f"a media dos numeros e: {media}")

4
# Recebe o número do usuário
numero = int(input("Digite um número para calcular a tabuada: "))

# Calcula e mostra a tabuada usando um laço de repetição
print("Tabuada de", numero, ":")
for i in range(1, 11):
    resultado = numero * i
    print(numero, "x", i, "=", resultado)

5
# Calcula e mostra a tabuada usando um laço de repetição
for i in range(1, 11):
  for j in range(2, 20):
   resultado = i * j
   print(i, "x", j, "=", resultado)

6
for i in range (1, 21):
   print (i)

   print (list(range))

7
for i in range(1,51):
  if i % 2 == 1:
    print(i)

8
#Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

n1 = int(input("digite um numero:"))
n2 = int(input("digite outro numero: "))

for u in range(n1+1, n2):
  print(u)

9
lojaB = 54000
lojaA = 0

for i in range(5):
  valor = int(input("digite um valor"))
  lojaA += valor

if lojaB > lojaA:
  print("Loja b foi maior")
elif lojaB == lojaA:
  print("foi igual")
else:
  print("loja A foi maior")

10
# Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.

impar = 0
par = 0

for i in range(10):
  numero = int(input(f"digite o {i+1} numero inteiro "))
  if numero % 2 == 0:
    par += 1
  else:
    impar += 1
print(f"numeros impares = {impar} e numeros pares = {par}")

11
salario = float(input("Digite o salario inicial do funcionario: "))
percentual = 0.015

for i in range (1996,2025):
  aumento = salario * percentual
  salario += aumento
  percentual *= 2
print(f"salario em {1} = (salario:.2f)")

12
for _ in range(5):
    nota = int(input("Digite uma nota entre zero e dez: "))
    if 0 <= nota <= 10:
        print("Nota válida:", nota)

    else:
        print("Valor inválido. Por favor, digite uma nota entre zero e dez.")
else:
    print("Limite de tentativas atingido. Tente novamente mais tarde.")

13
print("Valor da Compra - Porcentagem de Desconto - Valor Final")

valor_base = 500

for desconto_porcentagem in range(1, 26):
    desconto_real = valor_base * (desconto_porcentagem / 100)
    valor_final = valor_base - desconto_real
    print(f"R${valor_base:.2f} - {desconto_porcentagem}% - R${valor_final:.2f}")


    valor_base += 100

14
# Faça um programa que receba a idade de 15 pessoas e que calcule e mostre

ate15 = 0
de16ate30 = 0
de31ate45 = 0
de46ate60 = 0
mais60 = 0
for i in range(15):
  idade = int(input("Digite sua idade"))
  if idade >= 15:
    ate15 += idade
  elif 16 <= idade <=30:
    de16ate30 +=idade
  elif 31<=  idade <= 45:
    de31ate45 +=idade
  elif 46 <= idade <= 60:
    de46ate60 +=idade
  else:
    mais60 += 1
print(f"Quantidade de pessoas com idade ate 15 anos = {ate15} / Quantidade de pessoas com idade de 16 ate 30 {de16ate30}\ quantidade de pessoas com 31 ate45 {de31ate45}/ quantidade de pessoas com ate 45 ate 60 {de46ate60}/ quantidades de pessoas com mais 60 {mais60}")
print (f"`{((100 * ate15)/15):.2f}% das pessoas tem até 15 anos")
print (f"`{((100 * ate60)/15):.2f}% das pessoas tem até 60 anos")

15
base = float(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))

resultado = 1

for i in range(expoente):
  if base == 1:
    resultado *= base
15
print(f"{base} elevado a {expoente} é igual a {resultado}")

16
N = int(input("Digite um número inteiro "))
primos = []
divisoes = 0

for num in range(2, N + 1):
    primo = True
    for i in range(2, int(num**0.5) + 1):
        divisoes += 1
        if num % i == 0:
            primo = False
            break
    if primo:
        primos += [num]

print("Números primos entre 1 e", N, primos)
print("Número total de divisões realizadas:", divisoes)

# 1.	Faça um contador de número do 1 ao 10 e que mostre o maior numero entre eles

if for contador (1, 11):

